language: python
python: 3.6
env:
  - PIPENV_IGNORE_VIRTUALENVS=1
install:
  - pip install -r pipenv.txt
script:
  - pipenv check
  - pipenv install --dev
  - pipenv run flake8
  - pipenv run generate
notifications:
  email: dhunt@mozilla.com
