language: python
python: 3.6
install:
  - pip install -r requirements/pipenv.txt
script:
  - pipenv check
  - pipenv install --dev
  - pipenv run flake8
  - pipenv run generate
notifications:
  email: dhunt@mozilla.com
